# codecov-mcp - local gates (match CI)

CLIPPY_FLAGS := -D warnings -D clippy::all -D clippy::pedantic -D clippy::nursery
CARGO ?= cargo +stable
DOC_OUT ?= target/doc

.PHONY: build release lint test coverage deny doc doc-open doc-clean ci run help

help:
	@echo "Targets: build release lint test coverage deny doc doc-open doc-clean ci run"

build:
	$(CARGO) build

release:
	$(CARGO) build --release

lint:
	$(CARGO) fmt --check
	$(CARGO) clippy --all-targets -- $(CLIPPY_FLAGS)

test:
	$(CARGO) test --all-targets

## Requires cargo-llvm-cov + llvm-tools-preview. Writes coverage/lcov.info.
coverage:
	mkdir -p coverage
	RUSTUP_TOOLCHAIN=stable $(CARGO) llvm-cov --lcov \
		--ignore-filename-regex 'examples/|src/main\.rs|src/test_env\.rs' \
		--output-path coverage/lcov.info

## Requires `cargo install cargo-deny`.
deny:
	$(CARGO) deny check

## rustdoc → `docs/api-rust/` (GitHub Pages deploy source).
doc:
	RUSTDOCFLAGS='-D warnings' $(CARGO) doc --no-deps
	@test -d "$(DOC_OUT)" || (echo "missing $(DOC_OUT)"; exit 1)
	@rm -rf docs/api-rust
	@mkdir -p docs/api-rust
	@cp -a "$(DOC_OUT)/." docs/api-rust/
	@printf '%s\n' \
		'<!DOCTYPE html>' \
		'<html lang="en">' \
		'<head>' \
		'<meta charset="utf-8">' \
		'<meta http-equiv="refresh" content="0; url=codecov_mcp/index.html">' \
		'<title>codecov-mcp — Rust API docs</title>' \
		'<link rel="canonical" href="codecov_mcp/index.html">' \
		'<script>location.replace("codecov_mcp/index.html");</script>' \
		'</head>' \
		'<body><p><a href="codecov_mcp/index.html">codecov-mcp API documentation</a></p></body>' \
		'</html>' \
		> docs/api-rust/index.html
	@touch docs/api-rust/.nojekyll
	@printf '%s\n' \
		'# Rust API documentation (rustdoc)' \
		'' \
		'Open [`codecov_mcp/index.html`](codecov_mcp/index.html) (root [`index.html`](index.html) redirects there).' \
		> docs/api-rust/README.md
	@echo "docs/api-rust/ updated - open docs/api-rust/index.html"

doc-open: doc
	@xdg-open docs/api-rust/index.html 2>/dev/null \
		|| open docs/api-rust/index.html 2>/dev/null \
		|| echo "Open docs/api-rust/index.html in a browser"

doc-clean:
	rm -rf docs/api-rust
	mkdir -p docs/api-rust
	@printf '%s\n' \
		'# Rust API documentation (rustdoc)' \
		'' \
		'Generated by `make doc`. CI deploys this folder to GitHub Pages on `dev`.' \
		> docs/api-rust/README.md

ci: lint test doc

run: build
	$(CARGO) run --quiet
